import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";

import { SeverityPill, StatusPill } from "@/components/audit-ui";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useSystemAudit } from "@/lib/octiva-connection";

export default function FixesScreen() {
  const colors = useColors();
  const { data: audit, isLoading, isError, refetch, isRefetching } = useSystemAudit();
  if (isLoading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={colors.tint} /></ScreenContainer>;
  if (!audit || isError) return <ScreenContainer className="items-center justify-center px-8"><Text style={[styles.empty, { color: colors.text }]}>Connect Octiva on the System tab to load live remediation work.</Text></ScreenContainer>;
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><FlatList data={audit.findings} keyExtractor={(item) => item.id} onRefresh={refetch} refreshing={isRefetching} showsVerticalScrollIndicator={false} contentContainerStyle={styles.listContent} ListHeaderComponent={<View><Text style={[styles.kicker, { color: colors.muted }]}>LIVE REMEDIATION</Text><Text style={[styles.title, { color: colors.text }]}>Fix queue</Text><Text style={[styles.intro, { color: colors.muted }]}>Each action is derived from a current backend blocker or a missing runtime-evidence record, not a hand-maintained TypeScript queue.</Text><View style={[styles.callout, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="arrow.triangle.branch" color={colors.tint} size={18} /><Text style={[styles.calloutCopy, { color: colors.text }]}>Resolve a source-system condition, then pull to refresh. The companion will remove or update the item only when Octiva’s API does.</Text></View></View>} ListEmptyComponent={<View style={[styles.noItems, { backgroundColor: colors.surface, borderColor: colors.border }]}><StatusPill label="NO LIVE FINDINGS" tone="positive" /><Text style={[styles.noItemsTitle, { color: colors.text }]}>No remediation items returned</Text></View>} renderItem={({ item, index }) => <Pressable onPress={() => router.push("/(tabs)/findings")} style={({ pressed }) => [styles.row, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><Text style={[styles.number, { color: colors.muted }]}>{String(index + 1).padStart(2, "0")}</Text><View style={styles.rowCopy}><SeverityPill severity={item.severity} /><Text style={[styles.problem, { color: colors.text }]}>{item.title}</Text><Text numberOfLines={2} style={[styles.required, { color: colors.muted }]}>{item.required_fix}</Text></View><IconSymbol name="chevron.right" color={colors.muted} size={20} /></Pressable>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ listContent: { paddingBottom: 104 }, kicker: { fontSize: 11, fontWeight: "800", letterSpacing: 0.85, marginTop: 10 }, title: { fontSize: 31, fontWeight: "800", letterSpacing: -1.05, marginTop: 4 }, intro: { fontSize: 14, lineHeight: 20, marginTop: 8 }, callout: { alignItems: "flex-start", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 10, marginBottom: 20, marginTop: 17, padding: 14 }, calloutCopy: { flex: 1, fontSize: 13, fontWeight: "700", lineHeight: 19 }, row: { alignItems: "flex-start", borderRadius: 17, borderWidth: 1, flexDirection: "row", gap: 11, marginBottom: 10, padding: 14 }, number: { fontSize: 11, fontWeight: "900", letterSpacing: 0.7, paddingTop: 3 }, rowCopy: { flex: 1 }, problem: { fontSize: 15, fontWeight: "800", lineHeight: 20, marginTop: 7 }, required: { fontSize: 12, fontWeight: "600", lineHeight: 18, marginTop: 5 }, empty: { fontSize: 15, fontWeight: "700", lineHeight: 22, textAlign: "center" }, noItems: { alignItems: "center", borderRadius: 17, borderWidth: 1, padding: 22 }, noItemsTitle: { fontSize: 15, fontWeight: "800", marginTop: 10 }, pressed: { opacity: 0.75, transform: [{ scale: 0.985 }] } });
